torchbox/torchbox-frontend

package.json, src/components/header/header.js, yarn.lock
@chris-lawton please could you review - I've used the body-scroll-lock plugin as per your suggestion.
=> Prevents body from scrolling when mobile menu is open

src/components/streamfield-block/streamfield-block.js, src/templates/case-studies/case-study-listing.js, src/templates/person/person.js
@chris-lawton ready for review - a quick one.
=> Fix load more case studies text

src/components/quote-slider/quote-slider.js
Accidentally missed from previous merge.
=> Pause testimonials on hover

src/components/blogs-listing-block/blogs.js, src/components/case-studies-block/case-studies-block.js, src/components/contact-detailed/contact.js, src/components/contact/contact.js, src/components/filter-tags/filter-tags.js, src/components/header/header.js, src/components/jobs-listing-block/jobs-block.js, src/components/nav-link/nav-link.js, src/components/quote-slider/quote-slider.js, src/components/streamfield-block/streamfield-block.js, src/components/theme-provider/theme-provider.js, src/templates/case-studies/case-study-listing.js, src/templates/case-study/case-study.js
Fixes a mass of console errors that I was seeing locally.
=> 69 error fixes

src/components/theme-provider/themes.js, src/styles/_vars.scss
@chris-lawton this one is just a colour update.
=> Get rid of accessible dark green and use dark blue instead

src/components/nav-link/nav-link.module.scss
@chris-lawton a super quick one
=> Fixing header link hover at desktop

src/templates/blogs/index.js, src/templates/case-studies/index.js
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/101
Requires torchbox/wagtail-torchbox#160
=> [101] Use SEO title on the work and blog index page

src/components/author-block/author-block.js, src/components/process-block/process-block.js, src/components/services-listing-block/services-block.js, src/components/streamfield-block/streamfield-block.js, src/components/team-listing-block/team-listing-block.js, src/components/testimonials-block/testimonials-block.js, src/fragments/images.js, src/templates/case-study/index.js, src/templates/person/index.js, src/templates/person/person.js, src/templates/service/service-page.js, src/templates/team/team-listing.js
=> Accessibility continued

src/templates/blog-post/index.js, src/templates/blogs/index.js, src/templates/case-studies/index.js, src/templates/case-study/index.js, src/templates/culture/index.js, src/templates/jobs/index.js, src/templates/person/index.js, src/templates/service/index.js, src/templates/service/service-page.js, src/templates/standard/index.js, src/templates/team/index.js
Adds the seo search description
=> Add seo description

src/templates/blog-post/index.js, src/templates/case-study/index.js
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/82
=> [82] Don't repeat case studies/blog posts on the same page

src/components/layout/layout.js, src/templates/culture/index.js, src/templates/service/index.js, src/templates/service/service-page.js
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/91
=> [91] Pass "location" via props

src/templates/culture/culture-page.module.scss
Another small one for you @chris-lawton
=> Ensure culture page image doesn't cut off the people at shorter screens

src/styles/_global.scss, src/templates/culture/culture-page.js, src/templates/culture/culture-page.module.scss, src/templates/culture/index.js
Relies on torchbox/wagtail-torchbox#163 being merged to the backend
codebase.
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/66
=> [66] Make it possible to hide strapline

src/components/blog-link/blog-link.module.scss, src/components/footer/footer.module.scss, src/components/hero/hero.module.scss, src/components/nav-link/nav-link.module.scss, src/components/process-block/process-block.module.scss, src/styles/_grid.scss, src/styles/_vars.scss
@chris-lawton some last tweaks requested by ben -see https://projects.torchbox.com/projects/tbxcom-redesign/tickets/43
=> 43 final tweaks

src/components/nav-link/nav-link.module.scss, src/components/theme-provider/themes.js
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/141
=> [141] Set default subnav colour to primary

src/templates/service/index.js
Only for subservice pages.
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/136
BE PR - torchbox/wagtail-torchbox#169
=> [136] Do not fetch service for a service page

src/templates/service/index.js
Fix https://projects.torchbox.com/projects/tbxcom-redesign/tickets/128
=> [128] Pass service slug to help block

src/templates/jobs/index.js
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/138
Required backend code - torchbox/wagtail-torchbox#168
=> [138] Add strapline to jobs index

src/components/theme-provider/themes.js
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/140
=> [140] Set header icon colour (flame) for the dark theme

src/templates/service/index.js, src/templates/sub-service/index.js
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/127
=> [127] Display 5 blog posts on service pages

src/components/jobs-listing-block/jobs-block.module.scss
The same spacing as blogs.
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/142
=> [142] Delete grey borders between jobs & adjust margins

src/templates/service/index.js, src/utils/urls.js
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/62
=> [62] Add filter links to "more blogs" and "more work"

src/components/nav-link/nav-link.module.scss
Hopefully the last point from this never ending ticket: https://projects.torchbox.com/projects/tbxcom-redesign/tickets/43
=> Adjust navigation spacing - make it wider at an earlier breakpoint

src/templates/sub-service/index.js
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/153
=> Ensure the sub-service page queries the contact reasons

src/components/footer/footer.js
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/152
=> Make the copyright date show the current year

src/components/header/header.module.scss, src/components/hero/hero.module.scss, src/components/nav-link/nav-link.js, src/components/nav-link/nav-link.module.scss
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/145
=> [145] Mobile fixes

src/components/header/header.js, src/components/header/header.module.scss, src/components/layout/layout.js
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/146
=> [146] Add jump to top link into nested nav

src/templates/person/person.js
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/150
=> Fall back to intro if no alt intro has been entered

src/components/contact-detailed/contact.js, src/components/contact-detailed/contact.module.scss, src/components/header/header.js, src/components/header/header.module.scss, src/components/jobs-listing-block/jobs-block.module.scss, src/components/nav-link/nav-link.module.scss, src/components/quote-slider/quote-slider.module.scss, src/components/streamfield-block/streamfield-block.module.scss, src/components/testimonials-block/testimonials-block.js, src/components/testimonials-block/testimonials-block.module.scss, src/components/theme-provider/themes.js, src/images/icons/quote.svg
=> Crosss browser testing

gatsby-config.js, package.json, yarn.lock
Add `gatsby-plugin-sitemap` to generate sitemaps during build process.
=> Add sitemap plugin

src/components/header/header.module.scss, src/components/nav-link/nav-link.module.scss
@chris-lawton please could you review? See https://projects.torchbox.com/projects/tbxcom-redesign/tickets/185
=> Navigation tweaks - ticket 185

src/templates/case-study/case-study.js, src/templates/case-study/index.js, src/utils/urls.js
Uses backend change - torchbox/wagtail-torchbox#175. Please deploy
backend before the front-end.
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/189
=> [189] Use new related case studies field

src/components/layout/layout.js
Looks like a few of the errors listed in the ticket were already fixed. 
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/69
=> [69] Fix Layout propType error

src/pages/404/404.js, src/pages/404/404.module.scss
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/177
- Wrap strapline and link in new positioning div (using existing values)
- Add missing required SEO prop value to Layout
=> [177] Add link to 404 page. Add missing SEO prop value.

src/components/parent-page-link/parent-page-link.module.scss
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/163
- Remove pseudo element from parent link styles
=> [163] Remove pseudo element

README.md
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/207
=> Update new staging URL in README

_headers, src/components/rich-text/index.js, src/components/rich-text/rich-text.js, src/components/streamfield-block/streamfield-block.js, src/utils/urls.js
Requires back-end - torchbox/wagtail-torchbox#176
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/202
=> [202] De-serialize page links in rich text

src/templates/blogs/index.js
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/210
- Update prop value to match data
=> [210] Update contact data

src/styles/_typography.scss, src/styles/_vars.scss
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/211
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/212
Small font tweaks
=> [211] [212] Add font fallbacks. Add italic style for i element

src/components/streamfield-block/streamfield-block.module.scss, src/templates/case-study/index.js
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/213
=> [213]Add padding for the raw HTML StreamField block

package-lock.json, src/components/jobs-listing-block/jobs-block.js, src/templates/jobs/index.js, src/templates/jobs/jobs-listing.js
Requires deployment of back-end first - torchbox/wagtail-torchbox#180
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/214
=> [214] Use job ID as key in the mapping

src/components/streamfield-block/streamfield-block.module.scss
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/197
=> [197] Remove border

src/components/team-listing-block/team-listing-block.module.scss
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/184
Switch the font sizes
=> [184] Switch font sizes

src/components/streamfield-block/streamfield-block.module.scss
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/208
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/191
- Add margin to embed
- Add positioning and padding CSS for aspect ratio
=> [191][208] Add padding and embed positioning for aspect ratio

src/components/process-block/process-block.js, src/templates/culture/culture-page.js, src/templates/culture/culture-page.module.scss
This PR opened for code review only, still requires BE staging, FE staging, testing/acceptance before merging to master.
=> Render service processes description as richtext

src/components/jobs-listing-block/jobs-block.js, src/components/jobs-listing-block/jobs-block.module.scss, src/templates/jobs/index.js, src/templates/jobs/jobs-listing.js
This PR add's the description field to the JobsListing Block
=> Add description to job listing page

src/components/rich-text/rich-text.js, src/templates/jobs/index.js, src/templates/jobs/jobs-listing.js, src/templates/jobs/jobs-listing.module.scss
This PR add's an Intro to JobIndexPage:
=> Add into to jobs page
